// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDMQdT-4057yo0AsiKFIgo6bXiWu4fxj0s',
    appId: '1:297785753893:web:977030d22be8c8f0dc9acc',
    messagingSenderId: '297785753893',
    projectId: 'weave-chat-d4bfa',
    authDomain: 'weave-chat-d4bfa.firebaseapp.com',
    storageBucket: 'weave-chat-d4bfa.firebasestorage.app',
    measurementId: 'G-ESB0QL8HB8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC43173-GQdnPITmYCoReQBtzVDK03KrUg',
    appId: '1:297785753893:android:d3dfc8576d23d8afdc9acc',
    messagingSenderId: '297785753893',
    projectId: 'weave-chat-d4bfa',
    storageBucket: 'weave-chat-d4bfa.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBIRuqfSn1FwNzNUQMeZpCNtIi8T68LBbg',
    appId: '1:297785753893:ios:11096f1871ba76b8dc9acc',
    messagingSenderId: '297785753893',
    projectId: 'weave-chat-d4bfa',
    storageBucket: 'weave-chat-d4bfa.firebasestorage.app',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDMQdT-4057yo0AsiKFIgo6bXiWu4fxj0s',
    appId: '1:297785753893:web:3349692fbb1a3be8dc9acc',
    messagingSenderId: '297785753893',
    projectId: 'weave-chat-d4bfa',
    authDomain: 'weave-chat-d4bfa.firebaseapp.com',
    storageBucket: 'weave-chat-d4bfa.firebasestorage.app',
    measurementId: 'G-DCXSR3RF83',
  );
}
